---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vaultwarden
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: vaultwarden
  sources:
    - repoURL: https://gitlab.nobell.fr/nobell/kubernetes/vaultwarden.git
      targetRevision: main
      path: "overlays/prod1"
  syncPolicy:
    syncOptions:
    - createNamespace=true