---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: outline
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: outline
  sources:
    - repoURL: https://gitlab.nobell.fr/nobell/kubernetes/outline.git
      targetRevision: main
      path: "overlays/nbl-prod"
  syncPolicy:
    syncOptions:
    - createNamespace=true