---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: glance
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: glance
  sources:
    - repoURL: https://gitlab.nobell.fr/nobell/kubernetes/glance.git
      targetRevision: main
      path: "overlays/nbl-prod"
  syncPolicy:
    syncOptions:
    - createNamespace=true