apiVersion: v1
kind: Service
metadata:
  name: argocd
spec:
  type: NodePort
  sessionAffinity: ClientIP
  selector:
    app.kubernetes.io/name: argocd-server
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31000