apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - argocd.yaml
namespace: argocd
patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: argocd-server
    path: patches/add-proxy-env.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: argocd-repo-server
    path: patches/add-proxy-env.yaml

configMapGenerator:
- name: argocd-cm
  behavior: merge
  envs:
  - envs/argocd-cm

