apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    name: in-cluster
  project: default
  source:
    path: apps/overlays/lab2
    targetRevision: main
    repoURL: https://gitlab.enpos.fr/enpos/deployments/argocd.git
